### PR TITLE
fix: kubelet 1.20 device checkpoint support

### PR DESCRIPTION
**Pull request by aisensiy**
The checkpoint file `/var/lib/kubelet/device-plugins/kubelet_internal_checkpoint` format changed in kubelet 1.20 (https://github.com/kubernetes/kubernetes/blob/d72c056260e771e8cd01220203582de0c0015786/pkg/kubelet/cm/devicemanager/checkpoint/checkpoint.go#L33-L43) which will make the current code crash. 

The format of file changes from original:

```json
{
  "Data": {
    "PodDeviceEntries": [
      {
        "PodUID": "...",
        "ContainerName": "...",
        "ResourceName": "...",
        "DeviceIDs": [ # <-------- KEY PART
          "GPU-xxxx"
        ],
        "AllocResp": "..."
      }
    ],
    "RegisteredDevices": {
      "nvidia.com/gpu": [
        ...
      ]
    }
  }
}
```

To:

```json
{
  "Data": {
    "PodDeviceEntries": [
      {
        "PodUID": "...",
        "ContainerName": "...",
        "ResourceName": "...",
        "DeviceIDs": { # <-------- KEY PART
          "0": [
            "GPU-xxxx"
          ]
        },
        "AllocResp": "..."
      }
    ],
    "RegisteredDevices": {
      "nvidia.com/gpu": [
        ...
      ]
    }
  }
}
```

### CODE REVIEW

**Comment by mYmNeo** [comment]
Thank you for your commit, but you misunderstanding the checkpoint file of gpu-manager, gpu-manager use this file to recover deviceID, it doesn't care about other fields.

**Comment by aisensiy** [comment]
So you mean `PodDevicesEntry` should not contain any other fields?

**Comment by aisensiy** [comment]
> Thank you for your commit, but you misunderstanding the checkpoint file of gpu-manager, gpu-manager use this file to recover deviceID, it doesn't care about other fields.

I am not trying to change the structure of `/etc/gpu-manager/checkpoint/gpumanager_internal_checkpoint`. I am trying to fix the parse of `/var/lib/kubelet/device-plugins/kubelet_internal_checkpoint`.

**Comment by mYmNeo** [comment]
> > Thank you for your commit, but you misunderstanding the checkpoint file of gpu-manager, gpu-manager use this file to recover deviceID, it doesn't care about other fields.
> 
> I am not trying to change the structure of `/etc/gpu-manager/checkpoint/gpumanager_internal_checkpoint`. I am trying to fix the parse of `/var/lib/kubelet/device-plugins/kubelet_internal_checkpoint`.

I get your point.

**Pull request merged**
