### PR TITLE
follow nvidia doc to do device verify

### PR DESCRIPTION
**Pull request by pokerfaceSad**
As the describe in  [CUDA Tookit Doc #7.4](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#runfile-verifications), it is necessary to ensure device files exists after load kernel module by `modprobe nvidia` and `modprobe nvidia-uvm`.

This PR add some command lines(follow nvidia's shell script) to create the right device file if it not exists to enhance robustness.

### CODE REVIEW

**Comment by mYmNeo** [comment]
gpu-manager is running in the container with a private mount namespace, the devices created by gpu-manager are not existed in host mount namespace.

**Comment by pokerfaceSad** [comment]
> gpu-manager is running in the container with a private mount namespace, the devices created by gpu-manager are not existed in host mount namespace.

We don't need to create device files in host, but to ensure `/dev/nvidiactl` and `/dev/nvidia-uvm` are accessible for gpu-manager container because the topo scheduling based on NVML need access the GPU.

**Comment by mYmNeo** [comment]
> > gpu-manager is running in the container with a private mount namespace, the devices created by gpu-manager are not existed in host mount namespace.
> 
> We don't need to create device files in host, but to ensure `/dev/nvidiactl` and `/dev/nvidia-uvm` are accessible for gpu-manager container because the topo scheduling based on NVML need access the GPU.

I didn't get your point. Your codes show that you want to mknod for `/dev/nvidiactl` and `/dev/nvidia-uvm`, and the original code has checked the accessibilities of the two devices.

**Comment by pokerfaceSad** [comment]
@mYmNeo 
> the original code has checked the accessibilities of the two devices.

Do you mean these two lines? [allocator.go L288](https://github.com/tkestack/gpu-manager/blob/808ff8c29a361f04499ff62242cd56e4f93089f6/pkg/services/allocator/nvidia/allocator.go#L288) and [allocator.go L294](https://github.com/tkestack/gpu-manager/blob/808ff8c29a361f04499ff62242cd56e4f93089f6/pkg/services/allocator/nvidia/allocator.go#L294)

> I didn't get your point

I mean, if `/dev/nvidiactl` or `/dev/nvidia-uvm` is unaccessible and the corresponding device files is not exists, we should create the correct device files by `mknod` after load nvidia driver kernel module. (As the describe in CUDA Doc)

**Comment by mYmNeo** [comment]
> @mYmNeo
> 
> > the original code has checked the accessibilities of the two devices.
> 
> Do you mean these two lines? [allocator.go L288](https://github.com/tkestack/gpu-manager/blob/808ff8c29a361f04499ff62242cd56e4f93089f6/pkg/services/allocator/nvidia/allocator.go#L288) and [allocator.go L294](https://github.com/tkestack/gpu-manager/blob/808ff8c29a361f04499ff62242cd56e4f93089f6/pkg/services/allocator/nvidia/allocator.go#L294)
> 
> > I didn't get your point
> 
> I mean, if `/dev/nvidiactl` or `/dev/nvidia-uvm` is unaccessible and the corresponding device files is not exists, we should create the correct device files by `mknod` after load nvidia driver kernel module. (As the describe in CUDA Doc)

Leaving the device unaccessible is useful sometimes. For example, gpu-manager does not report resources to kubelet because of the unaccessible devices, this will notify users to check if node is prepared well.

**Comment by pokerfaceSad** [comment]
> > @mYmNeo
> > > the original code has checked the accessibilities of the two devices.
> > 
> > 
> > Do you mean these two lines? [allocator.go L288](https://github.com/tkestack/gpu-manager/blob/808ff8c29a361f04499ff62242cd56e4f93089f6/pkg/services/allocator/nvidia/allocator.go#L288) and [allocator.go L294](https://github.com/tkestack/gpu-manager/blob/808ff8c29a361f04499ff62242cd56e4f93089f6/pkg/services/allocator/nvidia/allocator.go#L294)
> > > I didn't get your point
> > 
> > 
> > I mean, if `/dev/nvidiactl` or `/dev/nvidia-uvm` is unaccessible and the corresponding device files is not exists, we should create the correct device files by `mknod` after load nvidia driver kernel module. (As the describe in CUDA Doc)
> 
> Leaving the device unaccessible is useful sometimes. For example, gpu-manager does not report resources to kubelet because of the unaccessible devices, this will notify users to check if node is prepared well.

Alright, thanks for your explanation.

**Pull request closed without merging**
